frr version 10.5.4_git
frr defaults traditional
hostname frr1
!
interface eth1
 ipv6 address 2001:db8:beba:cafe::2/126
exit
!
interface lo
 ip address 10.1.1.1/24
exit
!
router bgp 65001
 bgp router-id 10.1.1.1
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 neighbor 2001:db8:beba:cafe::1 remote-as 6500
 neighbor 2001:db8:beba:cafe::1 description WAN-IP-AS6500	
 neighbor 2001:db8:beba:cafe::1 capability extended-nexthop
 !
 address-family ipv4 unicast
  network 10.1.1.0/24
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8:beba:cafe::1 activate
 exit-address-family
exit
!

