frr version 10.5.4_git
frr defaults traditional
hostname frr2
!
interface eth1
 ipv6 address 2001:db8:beba:cafe::6/126
exit
!
interface eth2
 ip address 2.2.2.1/24
exit
!
interface lo
 ip address 172.16.2.1/24
exit
!
router bgp 65002
 bgp router-id 172.16.2.1
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 neighbor 2001:db8:beba:cafe::5 remote-as 6500
 neighbor 2001:db8:beba:cafe::5 description WAN-IP-AS6500
 neighbor 2001:db8:beba:cafe::5 capability extended-nexthop
 !
 address-family ipv4 unicast
  network 2.2.2.0/24
  network 172.16.2.0/24
 exit-address-family
exit
!
