frr version 8.4_git
frr defaults traditional
hostname R2
!
interface eth1
 description "Link to R1"
 ipv6 address 2001:db8:0:2::2/64
exit
!
interface eth2
 description "Link to R3"
 ipv6 address 2001:db8:0:3::1/64
exit
!
interface lo
 ipv6 address 2001:db8:beba:2:2:2:2:2/128
 ipv6 ospf6 area 0.0.0.0
exit
!
router bgp 65501
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 2001:db8:beba:1:1:1:1:1 remote-as 65501
 neighbor 2001:db8:beba:1:1:1:1:1 description IBGP-R1
 neighbor 2001:db8:beba:1:1:1:1:1 update-source lo
 neighbor 2001:db8:beba:1:1:1:1:1 capability extended-nexthop
 neighbor 2001:db8:beba:3:3:3:3:3 remote-as 65501
 neighbor 2001:db8:beba:3:3:3:3:3 description IBGP-R3
 neighbor 2001:db8:beba:3:3:3:3:3 update-source lo
 neighbor 2001:db8:beba:3:3:3:3:3 capability extended-nexthop
 !
 address-family ipv6 unicast
  neighbor 2001:db8:beba:1:1:1:1:1 activate
  neighbor 2001:db8:beba:3:3:3:3:3 activate
 exit-address-family
exit
!
