frr version 10.5.4_git
frr defaults traditional
hostname frr3
!
interface eth1
 ipv6 address 2001:db8:beba:cafe::a/126
exit
!
interface lo
 ip address 192.168.3.1/24
exit
!
router bgp 65003
 bgp router-id 192.168.3.1
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 neighbor 2001:db8:beba:cafe::9 remote-as 6500
 neighbor 2001:db8:beba:cafe::9 description WAN-IP-AS6500
 neighbor 2001:db8:beba:cafe::9 capability extended-nexthop
 !
 address-family ipv4 unicast
  network 192.168.3.0/24
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8:beba:cafe::9 activate
 exit-address-family
exit
!
