frr version 10.5.4_git
frr defaults traditional
hostname frr5
!
ip route 74.125.0.0/16 Null0
ip route 172.217.0.0/16 Null0
ip route 8.8.4.0/24 Null0
!
interface eth1
 ipv6 address 2001:db8:beba:c0ca::2/126
exit
!
interface lo
 ip address 8.8.8.8/24
exit
!
router bgp 15169
 bgp router-id 8.8.8.8
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 2001:db8:beba:c0ca::1 remote-as 6500
 neighbor 2001:db8:beba:c0ca::1 description CLI-ASN-6500
 neighbor 2001:db8:beba:c0ca::1 capability extended-nexthop
 !
 address-family ipv4 unicast
  network 8.8.4.0/24
  network 8.8.8.0/24
  network 74.125.0.0/16
  network 172.217.0.0/16
  neighbor 2001:db8:beba:c0ca::1 activate
 exit-address-family
exit
!
